### ISSUE TITLE
Error trying to join a local server

### ISSUE THREAD

**Issue by PedalHat29861** [fzzyhmstrs/piu#4]
Version: [pack_it_up-0.2.0+1.19.jar]
Full server log:
```
[11:22:33] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[11:22:33] [main/INFO]: Loading 75 mods:
	- appleskin 2.4.1+mc1.19
	- architectury 6.2.43
	- bookshelf 16.1.4
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective-fabric 4.36
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- emotecraft 2.2.2
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fiber 0.23.0-2 via collective-fabric
	- forgeconfigapiport 4.2.3
	- geckolib3 3.1.16
	- itemflexer 1.3.0
	- java 17
	- lazydfu 0.1.3
	- lithium 0.8.3
	- microconfig 2.2.1 via itemflexer
	- minecraft 1.19.2
	- notenoughcrashes 4.1.8+1.19.2
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- pack_it_up 0.2.0+1.19
	- placeholder-api 2.0.0-beta.5+1.19 via itemflexer
	- player-animator 0.3.0 via emotecraft
	- timeoutout 1.0.3+1.19.1
[11:22:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Servidores/Server%201.19.2%20fabric/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[11:22:33] [main/INFO]: Compatibility level set to JAVA_16
[11:22:33] [main/INFO]: Compatibility level set to JAVA_17
[11:22:33] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[11:22:34] [main/WARN]: Error loading class: net/minecraft/class_465 (java.lang.ClassNotFoundException: net/minecraft/class_465)
[11:22:34] [main/WARN]: @Mixin target net.minecraft.class_465 was not found pack_it_up.mixins.json:HandledScreenMixin from mod pack_it_up
[11:22:39] [main/INFO]: Building unoptimized datafixer
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tadpole_bucket is now minecraft:bucket.
[11:22:41] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 4.36.
[11:22:42] [main/INFO]: [STDOUT]: Flex your items!
[11:22:42] [main/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[11:22:42] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:22:44] [main/INFO]: Loaded 8 recipes
[11:22:44] [main/INFO]: Loaded 1179 advancements
[11:22:45] [main/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 2.248 ms
[11:22:45] [Server thread/INFO]: Starting minecraft server version 1.19.2
[11:22:45] [Server thread/INFO]: Loading properties
[11:22:45] [Server thread/INFO]: Default game type: SURVIVAL
[11:22:45] [Server thread/INFO]: Generating keypair
[11:22:45] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:22:45] [Server thread/INFO]: Using default channel type
[11:22:46] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:22:46] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:22:46] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[11:22:46] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:22:46] [Server thread/INFO]: Preparing level "world"
[11:22:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[11:22:49] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:49] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[11:22:50] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[11:22:50] [Worker-Main-3/INFO]: Preparing spawn area: 24%
[11:22:51] [Worker-Main-10/INFO]: Preparing spawn area: 89%
[11:22:51] [Server thread/INFO]: Time elapsed: 4651 ms
[11:22:51] [Server thread/INFO]: Done (5.071s)! For help, type "help"
[11:22:54] [Server thread/INFO]: PedalHat29861[/127.0.0.1:64615] logged in with entity id 224 at (-32.6109544116144, 68.5625, -82.84294143051021)
[11:22:54] [Netty Server IO #1/ERROR]: Error receiving packet 106
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeIdentifier(PacketByteBuf:638) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.writeRecipe(SynchronizeRecipesS2CPacket:50) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:179) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket:27) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:45) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:14) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.network.ClientConnection.sendInternal(ClientConnection:209) ~[?:?]
	at net.minecraft.network.ClientConnection.method_10761(ClientConnection:201) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:22:54] [Server thread/INFO]: PedalHat29861 joined the game
[11:22:54] [Server thread/INFO]: PedalHat29861 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
[11:22:54] [Server thread/INFO]: PedalHat29861 left the game
[11:22:54] [Server thread/WARN]: handleDisconnection() called twice
[11:27:08] [Server thread/INFO]: Stopping the server
[11:27:08] [Server thread/INFO]: Stopping server
[11:27:08] [Server thread/INFO]: Saving players
[11:27:08] [Server thread/INFO]: Saving worlds
[11:27:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[11:27:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[11:27:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[11:27:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[11:27:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:27:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:27:09] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

```

**Comment by fzzyhmstrs** [comment]
Thank you for the report! This is fixed in version 0.2.1
